import type { Metadata } from "next";
import Link from "next/link";
import ScrollReveal from "@/components/ScrollReveal";

export const metadata: Metadata = {
  title: "Privacy Policy | Lee Gordon",
  description: "Privacy policy for leegordon.design — how your data is handled when you visit this portfolio site.",
};

const sections = [
  {
    heading: "Overview",
    body: `This is a personal portfolio website for Lee Gordon Design. It is a static site with no user accounts, no contact forms, no newsletter signups, and no e-commerce. In short, this site collects as little about you as technically possible.`,
  },
  {
    heading: "What data is collected",
    body: `This site does not set cookies or run any first-party tracking scripts.\n\nHowever, this site is hosted on GitHub Pages (operated by GitHub, Inc., a subsidiary of Microsoft). GitHub Pages may collect standard web server log data when you visit — including your IP address, browser type, referring URL, and pages requested. This is standard infrastructure-level logging, not something Lee Gordon controls or processes directly.\n\nNo analytics platform (Google Analytics, Plausible, Fathom, etc.) is installed on this site.`,
  },
  {
    heading: "How information is used",
    body: `Lee Gordon does not collect, store, or process your personal data through this website.\n\nGitHub's handling of server log data is governed by their own privacy policy, available at github.com/privacy. They use this data to operate and maintain GitHub Pages infrastructure.`,
  },
  {
    heading: "Third-party services",
    body: `The only third-party service involved in delivering this site is GitHub Pages (github.com). No advertising networks, social media trackers, or analytics services have access to data generated by your visit.`,
  },
  {
    heading: "AI tools disclosure",
    body: `Lee Gordon uses AI tools — including Claude (Anthropic), Gemini (Google), and Cursor — as part of his professional design and development workflow. These tools assist in creating the work showcased on this site.\n\nNo visitor data from this website is shared with or fed into any AI system. AI tools are used solely as creative and productivity tools in Lee's own work process.`,
  },
  {
    heading: "Your rights",
    body: `If you are located in the European Economic Area (EEA) or the UK, you have rights under GDPR including the right to access, correct, or request deletion of personal data. Given that this site does not collect personal data directly, there is typically nothing to access or delete.\n\nIf you have questions or concerns, contact Lee directly at leegordo@gmail.com and he will respond within a reasonable timeframe.`,
  },
  {
    heading: "Contact",
    body: `Privacy questions or requests: leegordo@gmail.com\n\nLee Gordon Design\nMexico City, Mexico`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="pt-32 pb-24">
      {/* Header */}
      <section className="max-w-3xl mx-auto px-6 mb-16">
        <ScrollReveal>
          <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
            Legal
          </p>
        </ScrollReveal>
        <ScrollReveal delay={0.1}>
          <h1 className="font-display text-display-md font-bold text-white mb-6">
            Privacy{" "}
            <span className="text-gradient-accent">Policy</span>
          </h1>
        </ScrollReveal>
        <ScrollReveal delay={0.2}>
          <p className="text-white/40 text-sm">
            Effective date: February 27, 2026
          </p>
        </ScrollReveal>
      </section>

      {/* Divider */}
      <div className="max-w-3xl mx-auto px-6 mb-16">
        <div className="line-accent" />
      </div>

      {/* Content */}
      <section className="max-w-3xl mx-auto px-6">
        <div className="space-y-12">
          {sections.map((section, index) => (
            <ScrollReveal key={section.heading} delay={index * 0.05}>
              <div>
                <h2 className="font-display text-lg font-semibold text-white mb-4 flex items-center gap-3">
                  <span className="text-white/20 text-sm font-mono tabular-nums">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  {section.heading}
                </h2>
                <div className="pl-9 space-y-4">
                  {section.body.split("\n\n").map((paragraph, i) => (
                    <p key={i} className="text-white/50 text-base leading-relaxed">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </section>

      {/* Divider */}
      <div className="max-w-3xl mx-auto px-6 mt-16 mb-12">
        <div className="line-accent" />
      </div>

      {/* Footer note */}
      <ScrollReveal delay={0.3}>
        <div className="max-w-3xl mx-auto px-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <p className="text-white/25 text-xs">
            This policy may be updated occasionally. Check back for the latest version.
          </p>
          <Link
            href="/"
            className="text-white/40 hover:text-white text-sm transition-colors duration-300 flex items-center gap-2 flex-shrink-0"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to portfolio
          </Link>
        </div>
      </ScrollReveal>
    </div>
  );
}
