import type { Metadata } from "next";
import Link from "next/link";
import ScrollReveal from "@/components/ScrollReveal";

export const metadata: Metadata = {
  title: "DoodleHaus — Managed AI Campaign Generation",
  description:
    "Complete multi-channel campaigns from a single brief. Strategy, copy, creative assets, video — all generated by AI, verified by humans. From $500 per campaign.",
};

const painPoints = [
  {
    title: "Tool Fatigue",
    description:
      "You're paying for Jasper, Copy.ai, Canva, and three other subscriptions. Each does one thing. None of them talk to each other. Your 'AI stack' is just a more expensive version of doing it manually.",
  },
  {
    title: "Copy ≠ Campaign",
    description:
      "AI writing tools generate text. But a campaign isn't text — it's strategy, creative, copy, assets, and distribution working together. You still need humans to assemble the pieces.",
  },
  {
    title: "The $5K Agency Invoice",
    description:
      "Traditional agencies charge $5K–$25K per campaign and take 4–6 weeks. You're paying for overhead, account managers, and revision cycles — not output.",
  },
];

const steps = [
  { number: "01", title: "Brief", description: "You fill out a structured brief: audience, goals, channels, tone. Takes 10 minutes." },
  { number: "02", title: "Research", description: "AI analyzes your market, competitors, and audience signals. Produces a strategy document." },
  { number: "03", title: "Copy", description: "Multi-channel copy generated: email sequences, LinkedIn posts, ad copy, landing page text. All on-brand via your Brand Playbook." },
  { number: "04", title: "Creative", description: "Visual assets produced: social graphics, ad banners, email headers. Matched to your brand system." },
  { number: "05", title: "Video", description: "Short-form video generated via Veo. Product demos, social clips, ad spots. Premium tier." },
  { number: "06", title: "QA", description: "Every asset reviewed for brand consistency, accessibility, and quality. Human-in-the-loop verification." },
  { number: "07", title: "Deliver", description: "Complete campaign package delivered: organized by channel, ready to deploy. Strategy doc included." },
];

const features = [
  {
    title: "Multi-Channel Output",
    description:
      "LinkedIn posts, email sequences, ad creative, landing pages, and video — from a single brief. Every asset designed to work together as a cohesive campaign.",
  },
  {
    title: "Strategy, Not Just Copy",
    description:
      "Every campaign starts with AI-generated market research and a strategy document. You don't just get content — you get the thinking behind it.",
  },
  {
    title: "Choose Your AI Stack",
    description:
      "Three LLM tiers — Budget, Standard, and Premium — so you control quality and cost. Run costs from $0.50 to $12 per campaign. You pick what matters.",
  },
  {
    title: "Human QA, Every Time",
    description:
      "AI generates. Humans verify. Every campaign goes through brand consistency, accessibility, and quality checks before delivery. No hallucinated nonsense ships.",
  },
];

const playbookLayers = [
  {
    title: "Human Layer",
    description:
      "Brand voice, tone, values, audience profiles, and messaging frameworks. The strategic foundation that defines who you are and how you speak.",
  },
  {
    title: "Agent Layer",
    description:
      "Structured data that AI agents consume directly: prompt templates, guardrails, quality thresholds, and channel-specific rules. Your brand logic, codified.",
  },
  {
    title: "Automation Layer",
    description:
      "Integration specs, workflow triggers, and deployment rules. Connects your Brand Playbook to your actual marketing stack — CMS, email platform, ad accounts.",
  },
];

const pricingTiers = [
  {
    name: "Starter",
    price: "$500",
    unit: "per campaign",
    description: "Single-channel campaign with core copy and creative assets.",
    features: [
      "1 channel (email OR social OR ads)",
      "Strategy brief",
      "Copy package",
      "3–5 creative assets",
      "Brand voice matching",
      "Budget LLM stack",
    ],
    highlighted: false,
  },
  {
    name: "Standard",
    price: "$1,500",
    unit: "per campaign",
    description: "Multi-channel campaign with full copy, creative, and strategy.",
    badge: "MOST POPULAR",
    features: [
      "3–4 channels",
      "Full strategy document",
      "Complete copy package",
      "10–15 creative assets",
      "Brand Playbook update",
      "Standard LLM stack",
    ],
    highlighted: true,
  },
  {
    name: "Premium",
    price: "$3,500",
    unit: "per campaign",
    description: "Full-stack campaign with video, landing pages, and premium AI.",
    features: [
      "All channels + video",
      "Full strategy + market research",
      "Complete copy + creative",
      "20+ creative assets",
      "Video generation (Veo)",
      "Brand Playbook build or update",
      "Premium LLM stack",
      "Priority delivery",
    ],
    highlighted: false,
  },
];

export default function DoodleHausPage() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative pt-32 pb-24 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
              Product
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h1 className="font-display text-display-lg font-bold text-gradient-accent mb-6">
              DoodleHaus
            </h1>
          </ScrollReveal>
          <ScrollReveal delay={0.2}>
            <p className="font-display text-display-sm text-white/80 mb-6">
              Complete campaigns from a single brief. Strategy, copy, creative, video — done.
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.3}>
            <p className="text-lg text-white/60 max-w-2xl mx-auto leading-relaxed mb-10">
              DoodleHaus is a managed AI campaign platform. You send a brief — we return a full
              multi-channel campaign: strategy, copy, email sequences, ad creative, landing pages,
              and video. No tools to learn. No team to hire.
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.4}>
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 px-8 py-3 rounded-full bg-neutral-200 text-black font-medium hover:bg-white transition-all duration-300"
            >
              Request a Demo
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
          </ScrollReveal>
        </div>
      </section>

      <div className="line-accent" />

      {/* Problem */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
              The Problem
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="font-display text-display-md font-bold text-white mb-16">
              AI marketing tools gave everyone a typewriter.{" "}
              <span className="text-white/40">Nobody got a newspaper.</span>
            </h2>
          </ScrollReveal>
          <div className="grid md:grid-cols-3 gap-6">
            {painPoints.map((point, i) => (
              <ScrollReveal key={point.title} delay={0.1 * (i + 1)}>
                <div className="rounded-2xl bg-surface-50 border border-white/5 p-8 h-full">
                  <h3 className="font-display text-lg font-semibold text-white mb-3">
                    {point.title}
                  </h3>
                  <p className="text-white/50 leading-relaxed">{point.description}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      <div className="line-accent" />

      {/* How It Works — Vertical Timeline */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
              How It Works
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="font-display text-display-md font-bold text-white mb-16">
              Brief in. Campaign out.{" "}
              <span className="text-white/40">Seven steps, zero tools.</span>
            </h2>
          </ScrollReveal>
          <div className="relative">
            {/* Timeline line */}
            <div className="absolute left-8 top-0 bottom-0 w-px bg-white/10 hidden md:block" />
            <div className="space-y-8">
              {steps.map((step, i) => (
                <ScrollReveal key={step.number} delay={0.05 * (i + 1)}>
                  <div className="flex gap-6 md:gap-8 items-start">
                    <div className="relative z-10 flex-shrink-0 w-16 h-16 rounded-full bg-surface-50 border border-white/10 flex items-center justify-center">
                      <span className="font-display text-sm font-bold text-neutral-200">
                        {step.number}
                      </span>
                    </div>
                    <div className="pt-3">
                      <h3 className="font-display text-lg font-semibold text-white mb-2">
                        {step.title}
                      </h3>
                      <p className="text-white/50 leading-relaxed">{step.description}</p>
                    </div>
                  </div>
                </ScrollReveal>
              ))}
            </div>
          </div>
        </div>
      </section>

      <div className="line-accent" />

      {/* Features */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
              What You Get
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="font-display text-display-md font-bold text-white mb-16">
              A full campaign package.{" "}
              <span className="text-white/40">Not a pile of AI-generated drafts.</span>
            </h2>
          </ScrollReveal>
          <div className="grid md:grid-cols-2 gap-6">
            {features.map((feature, i) => (
              <ScrollReveal key={feature.title} delay={0.1 * (i + 1)}>
                <div className="rounded-2xl bg-surface-50 border border-white/5 p-8 h-full">
                  <h3 className="font-display text-lg font-semibold text-white mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-white/50 leading-relaxed">{feature.description}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Brand Playbook — Full-width section break */}
      <section className="py-24 px-6 bg-gradient-to-b from-transparent via-white/[0.02] to-transparent">
        <div className="max-w-4xl mx-auto">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6">
              Brand Playbook
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="font-display text-display-md font-bold text-white mb-6">
              Your brand, machine-readable.{" "}
              <span className="text-white/40">Not a PDF gathering dust.</span>
            </h2>
          </ScrollReveal>
          <ScrollReveal delay={0.2}>
            <p className="text-lg text-white/60 max-w-3xl leading-relaxed mb-16">
              Most brand guidelines live in a PDF nobody reads. DoodleHaus builds a Brand Playbook —
              a structured, machine-readable brand system with three layers that AI agents actually
              consume.
            </p>
          </ScrollReveal>
          {/* Stacked horizontal cards */}
          <div className="space-y-4">
            {playbookLayers.map((layer, i) => (
              <ScrollReveal key={layer.title} delay={0.1 * (i + 1)}>
                <div className="rounded-2xl bg-surface-50 border border-white/5 p-8 flex flex-col md:flex-row md:items-center gap-4 md:gap-8">
                  <div className="flex-shrink-0">
                    <span className="inline-flex px-3 py-1 rounded-full bg-white/5 border border-white/10 text-neutral-200 text-xs font-medium tracking-wider uppercase">
                      Layer {i + 1}
                    </span>
                  </div>
                  <div>
                    <h3 className="font-display text-lg font-semibold text-white mb-2">
                      {layer.title}
                    </h3>
                    <p className="text-white/50 leading-relaxed">{layer.description}</p>
                  </div>
                </div>
              </ScrollReveal>
            ))}
          </div>
          {/* Case study callout */}
          <ScrollReveal delay={0.4}>
            <div className="mt-12 rounded-2xl bg-surface-50 border border-white/5 p-8 text-center">
              <p className="text-white/60 mb-4">
                See how we built a Brand Playbook for StickerGiant — from strategy to automation.
              </p>
              <Link
                href="/contact"
                className="inline-flex items-center gap-2 text-neutral-200 hover:text-white transition-colors duration-300"
              >
                See a sample Brand Playbook
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </Link>
            </div>
          </ScrollReveal>
        </div>
      </section>

      <div className="line-accent" />

      {/* Pricing */}
      <section className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <ScrollReveal>
            <p className="text-neutral-200 text-sm font-medium tracking-[0.3em] uppercase mb-6 text-center">
              Pricing
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="font-display text-display-md font-bold text-white mb-4 text-center">
              Campaign pricing, not SaaS seats.
            </h2>
          </ScrollReveal>
          <ScrollReveal delay={0.2}>
            <p className="text-lg text-white/50 text-center max-w-2xl mx-auto mb-16">
              Pay per campaign or lock in a monthly retainer. No per-seat fees. No platform subscriptions.
            </p>
          </ScrollReveal>
          <div className="grid md:grid-cols-3 gap-6">
            {pricingTiers.map((tier, i) => (
              <ScrollReveal key={tier.name} delay={0.1 * (i + 1)}>
                <div
                  className={`relative rounded-2xl p-8 h-full flex flex-col ${
                    tier.highlighted
                      ? "bg-surface-50 border-2 border-neutral-200/20"
                      : "bg-surface-50 border border-white/5"
                  }`}
                >
                  {tier.badge && (
                    <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-neutral-200 text-black text-xs font-bold tracking-wider uppercase">
                      {tier.badge}
                    </span>
                  )}
                  <h3 className="font-display text-lg font-semibold text-white mb-2">
                    {tier.name}
                  </h3>
                  <div className="mb-4">
                    <span className="font-display text-display-sm font-bold text-white">
                      {tier.price}
                    </span>
                    <span className="text-white/40 text-sm ml-2">{tier.unit}</span>
                  </div>
                  <p className="text-white/50 text-sm mb-6">{tier.description}</p>
                  <ul className="space-y-3 mb-8 flex-grow">
                    {tier.features.map((feature) => (
                      <li key={feature} className="flex items-start gap-3 text-sm text-white/60">
                        <svg
                          className="w-4 h-4 text-neutral-200 flex-shrink-0 mt-0.5"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth={2}
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                        </svg>
                        {feature}
                      </li>
                    ))}
                  </ul>
                  <Link
                    href="/contact"
                    className={`inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full font-medium transition-all duration-300 ${
                      tier.highlighted
                        ? "bg-neutral-200 text-black hover:bg-white"
                        : "bg-white/5 border border-white/10 text-white/80 hover:border-white/30 hover:text-white"
                    }`}
                  >
                    {tier.highlighted ? "Request Demo" : "Get Started"}
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                    </svg>
                  </Link>
                </div>
              </ScrollReveal>
            ))}
          </div>
          {/* Retainer footnote */}
          <ScrollReveal delay={0.4}>
            <p className="text-center text-white/40 text-sm mt-8">
              Monthly retainers from $1,600/mo (4 Starter campaigns) to $9,500/mo (3 Premium + Brand Playbook maintenance).{" "}
              <Link href="/contact" className="text-neutral-200 hover:text-white transition-colors underline">
                Contact us
              </Link>{" "}
              for custom packages.
            </p>
          </ScrollReveal>
        </div>
      </section>

      <div className="line-accent" />

      {/* Bottom CTA */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <ScrollReveal>
            <div className="rounded-2xl bg-surface-50 border border-white/5 p-12 text-center">
              <h2 className="font-display text-display-sm font-bold text-white mb-4">
                Stop assembling campaigns from AI fragments.
              </h2>
              <p className="text-white/50 mb-8 max-w-lg mx-auto">
                Send a brief. Get a campaign. See what DoodleHaus can do for your next launch.
              </p>
              <Link
                href="/contact"
                className="inline-flex items-center gap-2 px-8 py-3 rounded-full bg-neutral-200 text-black font-medium hover:bg-white transition-all duration-300"
              >
                Request a Demo
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </Link>
            </div>
          </ScrollReveal>
        </div>
      </section>
    </div>
  );
}
